### ISSUE TITLE
Update diffs dependency

### ISSUE THREAD

**Issue by nicolasroger17** [nDmitry/grunt-postcss#100]
Your dependency diffs just made a major update and your code doesn't work properly with it.
You should lock to a <3.0 version or update the code.
https://github.com/kpdecker/jsdiff/releases

**Comment by nDmitry** [comment]
It is already locked on 2.x.x https://github.com/nDmitry/grunt-postcss/blob/master/package.json#L30

**Comment by nicolasroger17** [comment]
Ok. I've reinstalled all my deps and then `postcss` stopped working. 
I thought it would be a problem with this diffs library cause the update times coincided.
I'll check again. Thx for the reply.
