### ISSUE TITLE
Always z-index or Multiple task

### ISSUE THREAD

**Issue by Bek81** [nDmitry/grunt-postcss#101]
Hi,
I sorely needed that the z-index works properly using the cssnano processors option in "watch" or at least that it can use 2 sub-tasks of postcss: a development one that excludes cssnano during the watch and another one (production) that includes that when I don't use watch. 

Can You help me, please?

Tnx in advance and regards.

**Comment by Bek81** [comment]
No one?

**Comment by melissakfreeman** [comment]
I've just had issues with z-index. Here is what my grunt file looks like with cssnano safe option set to true (doesn't "fix" your z-index).

        ```
postcss: {
            options: {
              map: true, // inline sourcemaps
              processors: [
                require('pixrem')(), // add fallbacks for rem units
                require('autoprefixer')(), // add vendor prefixes
                require('cssnano')({ "safe": true }) // minify the result
              ]
            },
            dist: {
              src: 'css/style.css',
              dest: 'style.css'
            }
        }
```

**Comment by Bek81** [comment]
I resolved to exclude completely cssnano in postcss task, leaving the task to minimize to another package, only in "production".
