### ISSUE TITLE
Add postcss-load-config (postcss.config.js)

### ISSUE THREAD

**Issue by michael-ciniawsky** [nDmitry/grunt-postcss#109]
@nDmitry 👋 Based on a discussion a while ago [here](https://github.com/postcss/postcss/issues/813) we agreed upon making [postcss-load-config](https://github.com/michael-ciniawsky/postcss-load-config) a defacto standard for config loading. I'm neither familiar with grunt itself nor writing a plugin for it 🙃 , but would you generally interested in supporting `postcss.config.js` in `grunt-postcss`?

**Comment by michael-ciniawsky** [comment]
@nDmitry friendly ping 😛

**Comment by alexilyaev** [comment]
This would be very much appreciated.
