### ISSUE TITLE
Bump postcss to v6

### ISSUE THREAD

**Issue by laytong** [nDmitry/grunt-postcss#112]
Stylelint and postcss-reporter have moved to post-css 6, it'd be nice if this package did so we can keep using it.

Thanks

**Comment by jozan** [comment]
I'm facing the same issue. :)

**Comment by conor-darcy** [comment]
Same issue with postcss-nested

**Comment by juniglee** [comment]
Hi guys, any updates on this?

**Comment by alexan** [comment]
you can override this dependency temporarily in your project with a `npm-shrikwrap.json`
```
{
  "dependencies": {
    "grunt-postcss": {
      "version": "0.8.0",
      "from": "grunt-postcss@0.8.0",
      "dependencies": {
        "postcss": {
          "version": "6.0.11",
          "from": "postcss@>=6.0.0 <7.0.0"
        }
      }
    }
  }
}
```

**Comment by nDmitry** [comment]
I'm going to update dependencies and drop node 0.12 support on this weekend.
