### ISSUE TITLE
PostCSS Runner Guidelines

### ISSUE THREAD

**Issue by ai** [nDmitry/grunt-postcss#18]
All PostCSS runners (like these grunt plugin) must pass [PostCSS Runner Guidelines](https://github.com/postcss/postcss/blob/master/Runner%20Guidelines.md).

@nDmitry Gulp and webpack plugins already passed. There is only you :).

**Comment by ai** [comment]
@nDmitry maybe I can help you?

Just please not ignore issues :). If you have no time, just write it and we will help you.

**Comment by nDmitry** [comment]
@ai I have no time nor interest for this, sorry. =) Can accept a PR and publish a release to comply the guidelines, it is no problem.

**Comment by ai** [comment]
BTW, why yoou is not interested? Without async API many plugins will not works with grunt-postcss.

**Comment by nDmitry** [comment]
I'm not saying it's not important, I'm just don't want to do this for some personal pragmatical reasons.

**Comment by ai** [comment]
What reasons?

**Comment by nDmitry** [comment]
@ai it doesn't matter as they're not related to PostCSS or this plugin. The issue must be closed and either it will be someone else with a pull request or me eventually.
