### ISSUE TITLE
Error with autoprefixer-core 5.2.0

### ISSUE THREAD

**Issue by quasiobject** [nDmitry/grunt-postcss#21]
Before creating this issue, I noticed that autoprefixer-core 5.2.0 was just released about 8 hours ago. Hopefully I'm not just jumping the gun here and it's just a dependency thing or something. I'm woefully unequipped to troubleshoot errors with Node modules, but would love to contribute.

That said, it seems when using 5.2.0 I'm getting a "undefined" error when Grunt gets to the postcss processors.

I tried it both ways:

```
var autoprefixer = require('autoprefixer-core');
...
processors: [
  autoprefixer({browsers: ['last 2 version', 'ie 9']}).postcss
]
```

```
processors: [
  require('autoprefixer-core')({browsers: ['last 2 version', 'ie 9']}).postcss
]
```

Both result in `Fatal error: undefined is not a function`

When switching back to autoprefixer-core 5.1.x, Grunt runs properly.

**Comment by renatoi** [comment]
Same problem here. I removed the ".postcss" and it worked for me. https://github.com/postcss/autoprefixer/issues/457

**Comment by quasiobject** [comment]
Removing .postcss seems to work for me, as well. Thanks @renatoi!

**Comment by BrianLenzo** [comment]
+1  I got the same failure and then I removed the .postcss and it worked.

**Comment by mattandrews** [comment]
:+1:, removing `.postcss` fixed the same issue.

**Comment by nDmitry** [comment]
Readme is updated.
