### ISSUE TITLE
Confusion on browsers option

### ISSUE THREAD

**Issue by Tickthokk** [nDmitry/grunt-postcss#23]
> The usage and options are similar with grunt-autoprefixer (except `browsers` option).

Can you elaborate on what you mean by "except browsers option"?  The wording's a little confusing.  Can you still use the `browerslist` file?  Can you still use an ['array', 'list']`?

Thanks!

**Comment by nDmitry** [comment]
It means there is no plugin-level `browsers` option in case of autoprefixer-core and all post-processors options are passed to the post-processors themselves.
