### ISSUE TITLE
Incomplete dependencies?

### ISSUE THREAD

**Issue by ain** [nDmitry/grunt-postcss#25]
Is there a reason why `autoprefixer-core` and `csswring` have to be installed explicitly instead of just having them in dependency descriptor?

**Comment by nDmitry** [comment]
Same reason you have to install Grunt plugins)

**Comment by ain** [comment]
I'm sorry, I'm not following. What I meant is that you have [csswring defined as a dependency](https://github.com/nDmitry/grunt-postcss/blob/master/package.json#L34), but not `autoprefixer-core`. Any particular reason for not having it in there?

**Comment by nDmitry** [comment]
It's a development dependency for testing purposes, when you do `npm install grunt-postcss` you only get `dependencies` and `peerDependencies` installed.
