### ISSUE TITLE
Question about csswring

### ISSUE THREAD

**Issue by jamierytlewski** [nDmitry/grunt-postcss#27]
Thanks for the plugin. Why are you showing csswring as part of the code? I didn't want all my code minified and it took a while to figure things out. Also, I like using the diff feature, but with csswring, the diff feature doesn't work.

Thanks

**Comment by nDmitry** [comment]
It's a usage example demonstrating how to use multiple post-processors. The diff feature is, of course, useless with minified code, but there is no `diff` option in the example.
