### ISSUE TITLE
Setting source map destination path

### ISSUE THREAD

**Issue by rarila** [nDmitry/grunt-postcss#28]
_postcss_'s documentation states:

>By default, PostCSS presumes that you want to save the source map as opts.to + '.map' and will use this path in the annotation comment. But you can set another path by providing a string value for annotation.

Setting ``option.map.annotation`` adds a comment with that path to the source map as expected.

That setting is ignored by _grunt-postcss_ and it is always [written to destination plus ``.map``](https://github.com/nDmitry/grunt-postcss/blob/master/tasks/postcss.js#L110).

It would be great to adopt the _postcss_ behavior to be consistent and to allow sourcemaps in different locations than the stylesheet. :smile:

**Comment by bobdenotter** [comment]
:+1:

**Comment by rarila** [comment]
A little addition: It would be great if you could put a path to a directory (string ends with a ``/`` or ``\``) in ``option.map.annotation`` as in grunt we can put an array of sourcefiles in ``src``. _postcss_ should then be called with ``path/to/maps/destinationfilename.map``.
