### ISSUE TITLE
Getting grunt-postcss to work

### ISSUE THREAD

**Issue by karneaud** [nDmitry/grunt-postcss#29]
Hey,

I am new to this and not sure what the correct syntaxes are concerning the postcss and autoprefixer.

see my stack post for details

http://stackoverflow.com/questions/30959449/autoprefixing-using-grunt-postcss

what is that weird error though?

**Comment by nDmitry** [comment]
I couldn't reproduce this, with such notation your source files should be replaced with prefixed versions. Anyway please try to update to the latest version.

**Comment by karneaud** [comment]
what is he latest version? I'm using "^5.0.2". And changed the process logic to 

`
	postcss :{
			options: {
				processors:[
					require('autoprefixer-core')({browsers:'last 8 versions'}).postcss
				]
			},dist: {
            files: [{
                expand: true,
                cwd: 'web/css/',
                src: ['**/*.css'],
                dest: 'web/css/'
            }]
        }
}
`

**Comment by karneaud** [comment]
Keep getting 

> Running "postcss:dist" (postcss) task
> Fatal error: undefined is not a function

**Comment by nDmitry** [comment]
`$ npm install grunt-postcss@0.5.4 autoprefixer-core`

And remove `.postcss` after the plugin function call (check out the readme).



On 06 Jul 2015, at 01:28, karneaud <notifications@github.com> wrote:

Keep getting

Running "postcss:dist" (postcss) task
Fatal error: undefined is not a function
