### ISSUE TITLE
How to define multiple tasks?

### ISSUE THREAD

**Issue by loominade** [nDmitry/grunt-postcss#35]
I'd like to define two postcss tasks with different files and different configs. I thought it would work like in [grunt docs](http://gruntjs.com/configuring-tasks#task-configuration-and-targets). So I created a ``modern``and an ``ancient``subtask:

```coffeescript
module.exports = (grunt) ->
  grunt.initConfig
    postcss:
      modern:
        options:
          processors: [
            require('autoprefixer-core')(browsers: 'last 2 versions')
            require('cssnano')()
          ]
        dist: src: 'modern.css'
      ancient:
        options:
          processors: [
            require('autoprefixer-core')(browsers: 'ie 6-8')
            require('cssnano')()
          ]
        dist: src: 'ancient.css'
```

But unfortunately they wont be executed like that. What should I do?

**Comment by nDmitry** [comment]
https://github.com/nDmitry/grunt-postcss/blob/master/Gruntfile.js#L25

**Comment by joshdick** [comment]
It looks like Grunt subtasks indeed are not executing as expected, even when I have multiple subtasks defined?

**Comment by danillewin** [comment]
@nDmitry, is there a way to implement subtasks without using _load-grunt-tasks_?

**Comment by vlrprbttst** [comment]
@nDmitry could you elaborate more? I have the same problem as #67 but from https://github.com/nDmitry/grunt-postcss/blob/master/Gruntfile.js#L25 I can't understand what the config in my case should be. i tried on stackoverflow too but i got no help: http://stackoverflow.com/questions/35341713/postcss-with-subtasks-not-working

could you suggest a solution? thanks!

**Comment by russelgauthier** [comment]
I have been trying the same thing and I get the same issue. I can't create subtasks. I tried several syntaxes and even one that was identical to the Gruntfile provided above. It didn't work for me.
