### ISSUE TITLE
multiple srcs not working - only uses last src?

### ISSUE THREAD

**Issue by jayenashar** [nDmitry/grunt-postcss#36]
I'm having a weird issue and think I must be doing something wrong, but I can't figure it out, so maybe it is an issue with this plugin.  I have the postcss config below and `postcss:sass` works fine, but `postcss:async` does not.  Basically when `target/main/css/async/**/*.css` matches a file, `src/main/webapp/css/async.css` contains the processed version of _only_ that file.  deleting the file lets `src/main/webapp/css/async.css` be the processed version of `src/main/css/async/**/*.css`.  What's happening here?  Does postcss not support multiple srcs?

        postcss: {
            options: {
                processors: [
                    require('autoprefixer-core')({browsers: '> 1%'}),
                    require('csswring')
                ]
            },
            sass: {
                files: {
                    //i can simplify this with http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically rename option but it's not worth it as it makes it less legible
                    'src/main/webapp/css/ie.css': 'target/main/css/ie.css',
                    'src/main/webapp/css/print.css': 'target/main/css/print.css',
                    'src/main/webapp/css/screen.css': 'target/main/css/screen.css'
                }
            },
            async: {
                src: ['src/main/css/async/**/*.css', 'target/main/css/async/**/*.css'],
                dest: 'src/main/webapp/css/async.css'
            }
        },

**Comment by nDmitry** [comment]
You're trying to concatenate multiple files into one, so you should do it with grunt-contrib-connect and then run grunt-postcss on the output file. Or it's possible to save files separately, to do this you can just omit the file name in `dest`.

**Comment by jayenashar** [comment]
ok, thanks.  i just assumed grunt-postcss would do the concat, like grunt-contrib-uglify.  i discovered shortly after opening this issue that grunt-sass also doesn't concat (only uses the first src).  solved this with libsass 3.2's @import, thanks.
