### ISSUE TITLE
browsers error

### ISSUE THREAD

**Issue by vlrprbttst** [nDmitry/grunt-postcss#39]
with autoprefixer i used to have this configuration

```browsers : ['> 5%', 'last 2 version', 'ie 8', 'ie 9']```

this doesn't work anymore, it gives an error. for example if I want support IE9, i write

```require('autoprefixer-core')({browsers: 'last 2 version','ie9'}),```

but it gives me an error:
```>> SyntaxError: Unexpected token }```

how do I add more browsers in the gruntfile now?
thanks! :)

**Comment by vlrprbttst** [comment]
ok, i figured it out. the new syntax is

```require('autoprefixer-core')({browsers: 'last 2 version, IE 9'})```

and the reference is @ https://github.com/ai/browserslist

**Comment by nDmitry** [comment]
You forgot array literals here `browsers: 'last 2 version','ie9'`, `Unexpected token` is a JavaScript syntax error.
