### ISSUE TITLE
Fatal error: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by jephjohnson** [nDmitry/grunt-postcss#40]
I keep getting the error mentioned above when compiling. If I comment out "require('cssnano')()" the build works fine. Nothing has changed in my grunt fine and was working properly up until an hour ago..Any thoughts?

**Comment by nDmitry** [comment]
What does `grunt postcss -v` print?

**Comment by jonknapp** [comment]
Not sure if this helps at all, but I started experiencing errors with `cssnano` in node v0.10.33, but it was running fine with `iojs-v2.3.3` when I switched with nvm locally.

**Comment by jonknapp** [comment]
I just updated Node to `v0.12.7` and `cssnano` ran fine.  #ymmv (your mileage may vary)

**Comment by jephjohnson** [comment]
@nDmitry - Running "postcss:dist" (postcss) task
Verifying property postcss.dist exists in config...OK
Files: css/global.css
Options: processors=[{},null,{"plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"cssnano","postcssVersion":"4.1.16","version":"4.1.16"}], map, diff=false, safe=false
Reading css/global.css...OK
Fatal error: Cannot read property 'split' of undefined
SDGL1388bb8ec:city-lift jjohnson29$

**Comment by jephjohnson** [comment]
@jonknapp - I am running the latest. 
node -v
v0.12.7

**Comment by dguhl** [comment]
I get the same error with 'map'.

Fatal error: Cannot read property 'map' of undefined

I followed your guide, though. Commenting cssnano out helps getting rid of it.

**Comment by nDmitry** [comment]
Looks like cssnano compatibility problems with different versions of node and postcss.
