### ISSUE TITLE
Postcss only reads last file in array of sources (src:)

### ISSUE THREAD

**Issue by fingermaster** [nDmitry/grunt-postcss#42]
postcss: {
      options: {
        map: true,
        processors: [
          require('postcss-nesting')({ /* options */ }),
          require('pixrem')(), // add fallbacks for rem units
          require('autoprefixer-core')({browsers: 'last 3 versions'}), // add vendor prefixes
          require('cssnano')() // minify the result
        ]
      },
      dist: {
        src: ['css/abc.css', 'css/slick.css', 'css/slick-theme.css'],
        dest: 'build/css/app.css'
      }
    },

**Comment by nDmitry** [comment]
You can't concatenate files with grunt-postcss, use grunt-contrib-concat to do this.
