### ISSUE TITLE
create sprites

### ISSUE THREAD

**Issue by tselishev-semen** [nDmitry/grunt-postcss#44]
Hi, I would like to use your ''grunt-postcss'' plugin , but I need support for creating sprites. For postcss I found only https://libraries.io/npm/postcss-sprites for creating sprites. How to do it in your plugin?

**Comment by nDmitry** [comment]
`$ npm install grunt-postcss postcss-sprites`

```
postcss: {
  options: {
    processors: [
      require('postcss-sprites')(options)
    ]
  },
  dist: {
    // ...
  }
}
```

**Comment by tselishev-semen** [comment]
Thank. I will try to use so and then I'll write here about the result
