### ISSUE TITLE
options: {map: false} delete previous sourcemap comment from css

### ISSUE THREAD

**Issue by delka** [nDmitry/grunt-postcss#46]
If I set 
```
    options: {
      map: false,
```
PostCSS should won't create or update sourcemaps!
But it **delete** previous sourcemap comment from result css: `/*# sourceMappingURL=main.css.map */` so css-file no longer have sourcemap.

My config for PostCSS is default (from https://github.com/nDmitry/grunt-postcss).

Why I set `map: false`? I was try to make workaroud because PostCSS broked my sourcemap if I add Google MDL.css

**Comment by nDmitry** [comment]
If you process your file with PostCSS an old sourcemap become obsolete and you should no longer use it. Anyway you should open an issue here because this option is PostCSS API: https://github.com/postcss/postcss/issues

**Comment by delka** [comment]
Post: https://github.com/postcss/postcss/issues/486
