### ISSUE TITLE
Using external "browserlist" file

### ISSUE THREAD

**Issue by dominique-mueller** [nDmitry/grunt-postcss#48]
Is there any way that we can use an external "browserlist" file in the projects root folder ?
When setting no options for autoprefixer-core, the default browser list is being used instead of this file.

**Comment by nDmitry** [comment]
@ai isn't it built-in in autoprefixer-core?

**Comment by ai** [comment]
Yes it is. Maybe `from` option is missed for PostCSS?

**Comment by nDmitry** [comment]
Just tested it and `browserslist` file is working fine for me with latest version of grunt-postcss. Make sure you have placed the file at one level with gruntfile.js and it has correct name and syntax. https://github.com/ai/browserslist#config-file
