### ISSUE TITLE
Task targets don't seem to be working

### ISSUE THREAD

**Issue by Ghosh** [nDmitry/grunt-postcss#49]
I am not being able to specify, two tasks for this plugin.

For example, this is working.

```
postcss: {
  options: {},
  files: {}
}
```

But this is not:-
```
postcss: {
   dev: {
     options: {},
     files: {}
    },
    build: {
       options: {},
       files: {}
    }
}
```

When the second option is run, its unable to find the source file.

**Comment by nDmitry** [comment]
It's a Grunt feature, so you must be doing something wrong.

https://github.com/nDmitry/grunt-postcss/blob/master/Gruntfile.js#L25
http://gruntjs.com/configuring-tasks
