### ISSUE TITLE
Grunt subtasks not supported?

### ISSUE THREAD

**Issue by donut** [nDmitry/grunt-postcss#5]
Either I'm totally screwing this up, or subtasks are not supported with this plugin.

For example, the following pattern works fine for every other grunt task I've used:

``` coffeescript
  config.stylus = {}
  config.stylus.affiliate =
    options:
      compress:      off
      linenos:       on
      'include css': on
      'resolve url': on
      paths:         ["public/affiliate_items"]
    files: {}
  config.stylus.affiliate.files["public/affiliate_items/build/main.css"] = \
    "public/affiliate_items/main.styl"
  config.stylus.affiliate.files["public/affiliate_newsletters/build/main.css"] ="public/affiliate_newsletters/main.styl"
```

In this case the `stylus` object is the subtask definition. I can call it with `grunt stylus:affiliate`.  Here's my postcss grunt task config:

``` coffeescript
  config.postcss =
    options:
      map: yes
    affiliate_items:
      options:
        processors: [autoprefixer().postcss]
      dist: src: 'public/affiliate_items/build/*.css'
  config.postcss.affiliate_newsletters =
    options:
      processors: [
        autoprefixer(
          browsers: ['> 1%', 'last 4 versions', 'Firefox ESR', 'Opera 12.1']
        ).postcss
      ]
    dist: src: 'public/affiliate_newsletters/build/*.css'
```

With this, calling `grunt postcss:affiliate_items` or `grunt postcss:affiliate_newsletter` fails silently.

Am I totally messing something or does this task just not support sub-tasks?

**Comment by loominade** [comment]
might be related to #35

**Comment by russelgauthier** [comment]
I have been trying the same thing and I get the same issue. I can't create subtasks. I tried several syntaxes and even one that was identical to the Gruntfile provided above. It didn't work for me.

I generally don't close tickets until I've written a test. I don't see any. I might get back to this.
