### ISSUE TITLE
v0.6.0 shows PostCSS deprecated warnings

### ISSUE THREAD

**Issue by ntwb** [nDmitry/grunt-postcss#50]
After upgrading to v0.6.0 from v0.5.4 PostCSS a bunch of deprecated warnings are shown.

```
Container#eachInside is deprecated. Use Container#walk instead.
Node#between is deprecated. Use Node#raws.between
Rule#_selector is deprecated. Use Rule#raws.selector
Node#_value was deprecated. Use Node#raws.value
Node#_important was deprecated. Use Node#raws.important
Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Node#before is deprecated. Use Node#raws.before
Node#after is deprecated. Use Node#raws.after
Node#semicolon is deprecated. Use Node#raws.semicolon
```
I only see a subset of the above warnings, the above list was taken from the last `grunt-postcss` Travis CI job here: https://travis-ci.org/nDmitry/grunt-postcss/jobs/76824445

My Gruntfile.js I tested this with -> https://core.trac.wordpress.org/browser/trunk/Gruntfile.js

This also relates to this issue (I think) https://github.com/stylelint/stylelint/issues/363

**Comment by nDmitry** [comment]
You're using plugins that weren't updated yet for PostCSS 5.0.

**Comment by ntwb** [comment]
Yes Dmitry, you are correct, my bad, sorry :)

I looked at https://github.com/postcss/autoprefixer/blob/master/package.json and it's using v5.0.4, but in fact this is the package ready to go for Autoprefixer v6, it just hasn't been tagged and released yet, and the current Autoprefixer indeed still uses PostCSS v4.x and this is what was causing the deprecated warnings :smirk:
