### ISSUE TITLE
peerDependency

### ISSUE THREAD

**Issue by monolithed** [nDmitry/grunt-postcss#54]
I propose to use `postcss` as `peerDependency` like `grunt`.
It seems more consistent with npm 3.

**Comment by nDmitry** [comment]
peerDependencies won't automatically be installed by npm 3, so if we move postcss there, users will end up with a broken workflow after they update. Will be the same with grunt, of course, but at least with grunt it will be for all grunt plugins and users most likely will know what to do. Not sure if we want to do this with postcss dependency.

**Comment by monolithed** [comment]
@nDmitry, все верно. Для "домашних" пользователей ничего не изменится, а те собирает гигабайтные тарболы и доставляют их на боевые сервера скажут спасибо. 
Неудобно, согласен, но `npm 3` подскажет чего не хватает при установке. 
Не зря же в `npm 3` перешли на плоские структуры директорий.

**Comment by nDmitry** [comment]
Надо подумать или посмотреть что будет после выхода npm 3. Каждый плагин декларирует свою версию postcss и этот плагин тоже, npm 3 по возможности будет распрямлять дерево, поэтому с peerDependencies или без зависимости на файловой системе, если я правильно понимаю, будут настолько плоскими, насколько возможно.

**Comment by monolithed** [comment]
@nDmitry, npm 3 уже давно [зарелизился](https://www.npmjs.com/package/npm). 
Кстати хороший вопрос, я не знаю как будет вести себя npm если установленная версия будет конфликтовать с требуемыми.

**Comment by nDmitry** [comment]
I have decided to relax postcss dependency version as much as possible so that all plugins depending from v5.x.x will reuse postcss dependency when possible.
