### ISSUE TITLE
processors issue: Autoprefixer

### ISSUE THREAD

**Issue by hitmands** [nDmitry/grunt-postcss#56]
#### I tried to open this ticket in postcss/autoprefixer, but they told me to open here.
grunt task:

I've some difficult to run autoprefixer with grunt-postcss!
All works fine if I don't call autoprefixer with options, ex:
```javascript
options: {
      map: false,
      processors: [
        autoprefixer
      ]
    }
```

I've a problem when I do the following:
```javascript
options: {
      map: false,
      processors: [
        autoprefixer({ browsers: [ 'last 2 versions' ] /*, ecc... */ })
      ]
    }
```
___
running grunt postcss --verbose I obtain:
```
Options: processors=[null], map=false, diff=false, safe=false
```

and, of course, nothing happens to my css!

Can anyone help me?

**Comment by hitmands** [comment]
@ai suggested me to try:
```
autoprefixer(opts).postcss
```
but the result is  ***Cannot read property 'postcss' of undefined***,
is it possible that `require('autoprefixer')({})` returns undefined?

**Comment by kylealwyn** [comment]
Same issue here

**Comment by adamsheridan** [comment]
Same for me also, might rollback to grunt-autoprefixer as that was working for me.

**Comment by nDmitry** [comment]
Make sure you're using the latest version of grunt-postcss and installing `autoprefixer` package (not `autoprefixer-core`) requiring it like this:

```
require('autoprefixer')({})
```

**Comment by kylealwyn** [comment]
Running grunt-postcss ^0.6.0  and autoprefixer ^6.0.3

![screen shot 2015-10-14 at 1 08 59 pm](https://cloud.githubusercontent.com/assets/14184138/10496306/f41fb716-7274-11e5-8b3e-c29c4c3d55f9.png)

![screen shot 2015-10-14 at 1 09 10 pm](https://cloud.githubusercontent.com/assets/14184138/10496313/f90d8456-7274-11e5-8565-85d086b5e91a.png)

**Comment by cdll** [comment]
marked, same issue here~

**Comment by t1gor** [comment]
Anyone has a fix for this so far?

**Comment by nDmitry** [comment]
It is indeed logging processors=[null] in verbose mode, but plugins passed in this option are working. If nothing happens to your CSS please check that you have correct expectations about output CSS (maybe you're trying to prefix `box-shadow` with the default options, which of course won't work, or something like this).

Can't say more without a config, input and output CSS.
