### ISSUE TITLE
Processing sourceMaps

### ISSUE THREAD

**Issue by davetgreen** [nDmitry/grunt-postcss#57]
Hey @nDmitry 

I'm already using PostCSS for autoprefixing and px fallback for rems, but it's been suggested that PostCSS might be able to solve my sourceMap related issue.

At the moment, I'm using grunt-sass to generate both my initial .css files and their accompanying sourceMaps. However, when I use grunt-contrib-cssmin to minify my .css files, the sourceMaps are no longer accurate as a result.

At the moment I have the following:

**grunt-sass**

````
options: {
      sourceMap: true,
      sourceMapContents: true,
      // sourceMapRoot: 'assets/css',
      style: 'compressed'
    },
````
**grunt-postcss**

````
options: {
    map: {
      'prev': '<%= siteInfo.assets_path %>/<%= siteInfo.css_dir %>/',
      'inline': false,
      'sourcesContent': true,
    }
},
````

Everything else is as it should be in terms of src/dest paths etc.

I'm finding that the sourceMap file generated by PostCSS is no different to the original.

Furthermore, if I uncomment `sourceMapRoot` in my grunt-sass config, PostCSS throws the following fatal error:

````
Fatal error: "bower_components/normalize-scss/_normalize.scss" is not in the SourceMap.
````
Having `sourceMapRoot` on was crucial to me getting sourceMaps working with unminified CSS, so I fear this could be the showstopper?

So my questions are:

1) Am I barking up the wrong tree here with regards getting an updated sourceMap that accurately reflects the minified CSS?

2) Does PostCSS have any `sourceMapRoot` equivalent or workaround to prevent this error?

Thanks folks.

**Comment by nDmitry** [comment]
Hi, you need to update sourcemaps on every step involving changes for CSS files contents. grunt-contrib-cssmin has sourceMap option, try to enable that or use postcss minifier like cssnano (this way postcss will all the work with sourcemaps).

**Comment by nDmitry** [comment]
@davetgreen have you come to a solution?
