### ISSUE TITLE
Error: require' is not defined

### ISSUE THREAD

**Issue by CarlosSouza** [nDmitry/grunt-postcss#59]
Hi!

I've been using autoprefixer for quite some time, then I tried to move towards postcss, although I'm facing a problem with "require":

**The postcss task:**

```
    postcss: {
      options: {
        map: true,
        processors: [
          require('autoprefixer')({browsers: 'last 2 versions'}), // add vendor prefixes
          require('pixrem')(), // add fallbacks for rem units
        ]
      },
      dist: {
        src: 'css/*.css',
      },
    }
```

==

**It returns the following errors:**

```
   Gruntfile.js
     66 |          require('autoprefixer')({browsers: 'last 2 versions'}), // add vendor prefixes
                   ^ 'require' is not defined.
     67 |          require('pixrem')(), // add fallbacks for rem units
                   ^ 'require' is not defined.
```

Appreciate your help!

**Comment by Joelwarren** [comment]
I have the same issue, looking for a solution

**Comment by nDmitry** [comment]
`require` is a node.js global variable: https://nodejs.org/api/modules.html

Honestly I don't have any ideas how you guys managed to get it undefined of you're using grunt with node =)

**Comment by CarlosSouza** [comment]
In fact I was checking my Gruntfile.js with jshint, that's why I was getting this message.

**Comment by nDmitry** [comment]
You can set jshint's `node` option to `true` to disable such warnings for known globals.
