### ISSUE TITLE
Option to not produce transformed files 

### ISSUE THREAD

**Issue by Krinkle** [nDmitry/grunt-postcss#61]
Right now the basic functionality of PostCSS where no files are produced is not exposed in grunt-postcss.

I'd like to use this task in combination with [stylelint](https://github.com/stylelint/stylelint) as a linter. It would be useful to not have it unconditionally write to disk.

This would essentially allow users to configure grunt-postcss similar to [AtomLinter/linter-stylelint](https://github.com/AtomLinter/linter-stylelint/blob/aa719bf8b08330896d27df8602dcde241b650cde/index.js#L58-L64).

**Comment by nDmitry** [comment]
Could you please explain why someone would use a grunt plugin like this? I would go with postcss itself for an editor plugin like in your example.

**Comment by jdforrester** [comment]
Our use case is continuous integration, asserting that there aren't automatically detectable issues with a patch's CSS and if there are some, blocking merge without having the CI cluster making local changes to commits. This would allow us to replace csslint in our CI pipeline.

**Comment by nDmitry** [comment]
Well, let's merge it then)

**Comment by jdforrester** [comment]
Thank you. :-)
