### ISSUE TITLE
Allow for output filename different to source?

### ISSUE THREAD

**Issue by KingScooty** [nDmitry/grunt-postcss#65]
It would be nice if we change the output filename to keep the source file intact:

```js
dist: {
  src: {
   'public/stylesheets/style.min.css': 'public/stylesheets/style.css'
  }
}
```

**Comment by nDmitry** [comment]
Could you elaborate this please? You can configure Grunt to output wherever you like.

**Comment by KingScooty** [comment]
Well, I tried the above syntax and got an error. What would be the correct syntax to output to a new file instead of overwriting the source file?

**Comment by nDmitry** [comment]
dest/target syntax is deprecated as far as I know, besides you've got redundant `src` key there.

Anything modern from here should work: http://gruntjs.com/configuring-tasks
