### ISSUE TITLE
grunt-postcss does not respect seperate tasks (ie 'postcss:dev' and 'postcss:dist')

### ISSUE THREAD

**Issue by tconroy** [nDmitry/grunt-postcss#67]
with the following task configuration:

```
postcss: {
    dev: {
        options: {
            map: true,
            processors: [
                require('autoprefixer')({browsers: ['last 3 versions', 'ie 8', 'ie 9']}),
                require('pixrem')() // add px fallback for rem units
            ]
        }
    },
    dist: {
        options: {
            map: false,
            processors: [
                require('autoprefixer')({browsers: ['last 3 versions', 'ie 8', 'ie 9']}),
                require('pixrem')(), // add px fallback for rem units
                require('cssnano')() // minify the result
            ]
        }
    }
}
```

the `dist` task is always executed, even when explicitly running `grunt postcss:dev`. same issue as #35 .

**Comment by tconroy** [comment]
false alarm. I did not adhere to the proper config. Sorry 'bout that. :)

**Comment by vlrprbttst** [comment]
@tconroy i have the same exact problem and config you have! can you help? http://stackoverflow.com/questions/35341713/postcss-with-subtasks-not-working

**Comment by nDmitry** [comment]
@vlrprbttst you can read about targets in Grunt configuration http://gruntjs.com/configuring-tasks#task-configuration-and-targets

Basically, you don't need `dist` property inside each target (`dev`, `build`), `dist` is a name for the default target. So it goes like this postcss.dev.{options, src}, postcss.build.{options, src}. You can also specify common options at the top level (postcss.options) and overwrite them in targets.

**Comment by vlrprbttst** [comment]
@nDmitry thanks a lot, after banging my head against the wall for a bit i finally understand. thanks for the extra explanations too, it confirms my findings! great work btw, keep it up :+1:

**Comment by tconroy** [comment]
yup that's the same issue I had. Was simply structuring the  config incorrectly. :)

**Comment by vlrprbttst** [comment]
if this might be of some help for anyone, this is my working config:

        postcss: {

                dev: {
                    options: {
                        map: true,
                        processors: [
                            require('autoprefixer')({
                                browsers: 'last 2 version, IE 9'
                            }),
                            
                        ]
                    },
                    src: 'css/main.css'
                },
                build: {
                    options: {
                        map: false,
                        processors: [
                            require('autoprefixer')({
                                browsers: 'last 2 version, IE 9'
                            }),
                            require('cssnano')() // minify the result
                        ]
                    },
                    src: '../_site/css/main.css'
                }
        }, //postcss

**Comment by Kelderic** [comment]
I ran into a bit of confusion with this as well, because I wanted to have multiple tasks but also wanted to specify different destination files. So here is my config that is working:

````
		// ... concat happens first ...
		postcss: {
			prefix : {
				options: {
					processors: [
						require('autoprefixer')({browsers: 'last 2 versions'}), // add vendor prefixes 
					]
				},
				src: 'PATH/TO/'concat_stylesheet.css',
				dest: 'PATH/TO/'concat_stylesheet.css',
			},
			minify: {
				options: {
					processors: [
						require('cssnano')() // minify the result 
					]
				},
				src: 'PATH/TO/'concat_stylesheet.css',
				dest: 'PATH/TO/'concat_stylesheet.min.css',
			}
		},
````

Path/file names changed for readability of course. Basically the key is, even though my `src` and `dest` were inside of a `dist`, when we split into separate tasks, they need to be moved outside of the `dist`, to the same level as the `options`.
