### ISSUE TITLE
Fail on error instead of skipping file

### ISSUE THREAD

**Issue by jithin1987** [nDmitry/grunt-postcss#69]
I find that if any css file has a syntax error (in my case it was format of comment), postcss ignores it silently (I had `failOnError` option as `true`). Is there any way to make postcss fail grunt task ?

**Comment by jithin1987** [comment]
I've also reported this issue at postcss https://github.com/postcss/postcss/issues/620 , not sure where the problem is throwing error or catching/reporting error.

**Comment by nDmitry** [comment]
Can you provide an example of CSS that should throw an error?

On 31 Oct 2015, at 04:53, Jithin Emmanuel <notifications@github.com> wrote:

I find that if any css file has a syntax error (in my case it was format of comment), postcss ignores it silently (I had failOnError option as true). Is there any way to make postcss fail grunt task ?

**Comment by jithin1987** [comment]
Fails
```
.rule  {
  position: relative;
  color: red !important; //FIXME
  top: 10px;
}
```

Works
```
.rule {
  position: relative;
  top: 10px;
  color: red !important; //FIXME
}
```

both rules has invalid comment syntax, but somehow if error is in last value postcss is happy.

This is my grunt config for postcss.

```
    postcss: {
      options: {
        failOnError: true,
        processors: [
          require('autoprefixer')({browsers: 'last 2 versions'}),
          require('postcss-simple-vars')({variables: require('fuji-css')}),
          require('postcss-reporter')({throwError: true})
        ]
      },
      dist: {
        files: [{
          expand: true,
          ext: '.css',
          dest: 'dist/',
          src: ['css/*.css']
        }]
      }
    },
```

I have 3 css files at `css/` folder, when the error rule is present, I simple see status as 
`>> 2 processed stylesheets created.` . No information about the 3rd file, it's silently ignored.

**Comment by nDmitry** [comment]
You have specified `throwError` option for postcss-reporter, so the config is correct. So PostCSS doesn't throw anything about invalid comments.

**Comment by jithin1987** [comment]
Having the `postcss-reporter` there in the config does not make any difference, I just added it because I read somewhere that it can display error or throw errors. But even `postcss-reporter` does not show any error/warning. I see the same behavior without it.

**Comment by nDmitry** [comment]
I ment this issue: https://github.com/nDmitry/grunt-postcss/issues/64
But this is not the case, so it's a PostCSS issue.

**Comment by jithin1987** [comment]
@nDmitry version `0.7.1` fixes this issue as well. Thanks.
