### ISSUE TITLE
Cannot read property 'length' of undefined Use --force to continue.

### ISSUE THREAD

**Issue by AndyBean** [nDmitry/grunt-postcss#7]
I believe this error after trying to sort it out for well over an hour is actually related to a bug in the most recent version of autoprefixer and autoprefixer-core but it pops up in grunt  as you try to run the prefixing task.

    Running "postcss:dist" (postcss) task
    Warning: Cannot read property 'length' of undefined Use --force to continue.

All of the following combinations fail to work using the below script
```
postcss: {
            options: {
                processors: [
                    autoprefixer({ browsers: ['last 2 version'] }).postcss
                ]
            },
            dist: {
                src: './dist/css/*.css',
                dest: './dist/css'
            }
        },
```
^ That fails, as does, `dist: { src: './dist/css/*.css' }`, as does
```
dist: {
                    './dist/css/file1.css': './dist/css/file1x.css',
                    './dist/css/file2.css': './dist/css/file2x.css'
            }
```
Except the last example does not actually cause an error.

**Comment by interactionist** [comment]
I get the same issue :(

```
Running "autoprefixer:single" (autoprefixer) task
Warning: Cannot read property 'length' of undefined Use --force to continue.
```

My version:
```autoprefixer-core@5.1.11 (num2fraction@1.1.0, browserslist@0.2.0, postcss@4.0.6, caniuse-db@1.0.30000163)```
