### ISSUE TITLE
Support for preprocessors?

### ISSUE THREAD

**Issue by FezVrasta** [nDmitry/grunt-postcss#71]
Can we use postcss to convert LESS to CSS?

**Comment by nDmitry** [comment]
```
options: {
    syntax: require('postcss-less') // work with LESS directly
}
```

Don't know if `postcss-less` works, I just found it on github.

**Comment by FezVrasta** [comment]
I don't think it's the same `postcss` project... and it isn't a LESS compiler, its a LESS-like compiler

**Comment by nDmitry** [comment]
It's a custom syntax for PostCSS that lets you parse LESS, process it and save as CSS. Like the one for SCSS https://github.com/nDmitry/grunt-postcss#optionssyntax-optionsparser-optionsstringifier

**Comment by FezVrasta** [comment]
Sorry I must have visited the wrong project then... I'll check the right one

**Comment by FezVrasta** [comment]
Can't find it, may you link it to me please?

**Comment by nDmitry** [comment]
https://github.com/gilt/postcss-less

**Comment by FezVrasta** [comment]
Thanks.
