### ISSUE TITLE
Relative sourcemaps broken

### ISSUE THREAD

**Issue by quintenvk** [nDmitry/grunt-postcss#72]
Cross-referencing the following issue... https://github.com/postcss/autoprefixer/issues/554 

Basically, when upgrading Autoprefixer our relative paths in sourcemaps broke. Instead of using a directory relative to where the generated CSS file is, it uses a directory relative to the current working directory. Am I missing a setting here?

**Comment by quintenvk** [comment]
Found the issue. The plugin runs async, which causes our other tasks to further interfere with the files.

**Comment by nDmitry** [comment]
Well, it runs async, but within targets of postcss task in your gruntfile, so this can't be an issue. We have a test for sourcemaps with relative paths specified correctly, don't know how autoprefixer can be related to this.

Anyway if you can provide your config and some input files I could try to reproduce.

**Comment by nDmitry** [comment]
Closing it for now, if you post a config with files so I could reproduce it I'll try. At least need a list of grunt plugins that you use in order of execution.
