### ISSUE TITLE
Incorrect Version of Grunt-PostCSS on NPM

### ISSUE THREAD

**Issue by jgacuca567** [nDmitry/grunt-postcss#74]
I Installed `grunt-postcss` as of today, but the version still says 0.55 instead of 0.71 as posted on the NPM Page.

**Comment by nDmitry** [comment]
Could be 0.5.x required in your package.json.

**Comment by jgacuca567** [comment]
Try reinstall it on your side and let me know what version you get

On Thu, Nov 19, 2015 at 12:38 Dmitry Nikitenko <notifications@github.com>
wrote:

> Could be 0.5.x required in your package.json.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nDmitry/grunt-postcss/issues/74#issuecomment-158130779>
> .
>
-- 
James Gacuca
jgacuca@gmail.com
(202)-569-1159

**Comment by nDmitry** [comment]
0.7.1 of course, you can't get any other version doing simple `npm i grunt-postcss` unless you have a dependency declared in package.json.

**Comment by nDmitry** [comment]
Or maybe you're using a private registry or something, try specify registry option: `--registry https://registry.npmjs.com`.

**Comment by jgacuca567** [comment]
Ok will try redoing it with save dev
On Thu, Nov 19, 2015 at 12:55 Dmitry Nikitenko <notifications@github.com>
wrote:

> Or maybe you're using a private registry or something, try specify
> registry option: --registry https://registry.npmjs.com.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nDmitry/grunt-postcss/issues/74#issuecomment-158136364>
> .
>
-- 
James Gacuca
jgacuca@gmail.com
(202)-569-1159
