### ISSUE TITLE
Task throws an error when there is error in css file

### ISSUE THREAD

**Issue by VasiliDarozhkin** [nDmitry/grunt-postcss#76]
Hi,
If I do

*grunt postcss*

I get
 **Fatal error**: /my-path/style.css:193:
*39: Missed semicolon
     -webkit-box-shadow: 0 1px 1px rgba(0, 0, 0, 0.04)
                                      ^
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0.04);*

if there is no semicolon in the end of line ( in my example in the «-webkit-box-shadow:»)

**Comment by nDmitry** [comment]
So what's the problem exactly?)

**Comment by VasiliDarozhkin** [comment]
I think a syntax error in the css shouldn't prevent the plugin from doing its job.
I would suggest to display a worning to console and proceed to next file

**Comment by nDmitry** [comment]
You could get unpredictable results in browsers this way, so it should fail on syntax errors and it won't be changed. But you can use safe parser to fix syntax errors automatically: https://github.com/nDmitry/grunt-postcss#optionssyntax-optionsparser-optionsstringifier

**Comment by VasiliDarozhkin** [comment]
Thanks, I'll try it!
