### ISSUE TITLE
Dev Dependency Should Include pixrem and autoprefixer

### ISSUE THREAD

**Issue by jolesbi** [nDmitry/grunt-postcss#77]
`npm install grunt-postcss --save-dev` does not install pixrem or autoprefixer.

Both seem to be requirements for running `grunt build` properly.

I can add these as dev dependencies if you want me to make the PR.

**Comment by nDmitry** [comment]
And what is `grunt build` exactly? If it's a task in a gruntfile you're using then you should install all the dependencies you need in your project's package.json.
