### ISSUE TITLE
PostCSS Version

### ISSUE THREAD

**Issue by yeeyang** [nDmitry/grunt-postcss#82]
Wanted to suggest a minor change in the PostCSS version from
```
"dependencies": {
    "chalk": "^1.0.0",
    "diff": "^2.0.2",
    "es6-promise": "^3.0.2",
    "postcss": "^5.0.0"
  },
```

to 
```
"dependencies": {
    "chalk": "^1.0.0",
    "diff": "^2.0.2",
    "es6-promise": "^3.0.2",
    "postcss": "^5.0.14"
  },
```

**Comment by ntwb** [comment]
PostCSS v5.0.14 is included in the semantic version range `^5.0.0`, to update just run `npm update`

You can test this yourself and see semantic versioning in action http://semver.npmjs.com/

**Comment by ntwb** [comment]
That said, https://github.com/nDmitry/grunt-postcss/pull/84 will also update/fix/resolve this issue

**Comment by yeeyang** [comment]
Sounds good. Thanks for putting in the PR.
