### ISSUE TITLE
es6-promise polyfill breaks karma

### ISSUE THREAD

**Issue by danyshaanan** [nDmitry/grunt-postcss#88]
Heya.

My execution of Karma (via `grunt karma`) fails due to  [the line](https://github.com/nDmitry/grunt-postcss/blob/d577e0ce9599d317b175448e1541a7c8fad57347/tasks/postcss.js#L8):
```js
require('es6-promise').polyfill();
```

This happens with:

* karma v0.13.21
* grunt-karma v0.12.1
* grunt-postcss v0.7.2
* grunt v0.4.5
* node v5.5.0

The breakdown:

* `grunt postcss` by itself works fine whether `require('es6-promise').polyfill();` is there or not.
* `grunt karma` fails unless I prevent the loading of the "grunt-postcss" task, or comment out the `require('es6-promise').polyfill();` line. Failure output is: `Fatal error: Cannot read property 'length' of undefined`

So - Is there a way to make `require('es6-promise').polyfill();` optional? As in, via postcss's grunt config? (Also notice the polyfill's side effect is caused by loading the task, as opposed to running the task). If this solution is acceptable, I'll be happy to implement via a pull request.

If required, I can set up a little mock project that reproduces the issue.

Please advise.

**Comment by nDmitry** [comment]
Hi, I dropped node 0.10 support in the latest version (just published), so that polyfill is gone.

**Comment by danyshaanan** [comment]
Thanks! :100:
