### ISSUE TITLE
Process multiple files into a single file

### ISSUE THREAD

**Issue by redaxmedia** [nDmitry/grunt-postcss#90]
Hello,

I'd like to process multiple files and output the result into a <code>portal.min.css</code> file:

<pre>
postcss: {
    portal: {
        src: [
            'app/Resources/assets/css/reset.css',
            'app/Resources/assets/css/layout.css',
            'app/Resources/assets/css/misc.css'
        ],
        dest: 'web/css/portal.min.css',
        options: {
            processors: [
                require('postcss-custom-properties'),
                require('postcss-custom-media'),
                require('postcss-custom-selectors'),
                require('postcss-color-gray'),
                require('postcss-color-function'),
                require('autoprefixer')({
                    browsers: 'last 2 versions'
                }),
                require('cssnano')
            ]
        }
    }
},</pre>

The result <code>portal.min.css</code> only contains the processed content of <code>misc.css</code>. Does PostCSS support the concatenation of files or do I need to use <code>grunt-contrib-concat</code> before?

**Comment by cvillanujr** [comment]
Give this a try:
```
postcss: {
    portal: {
        options: {
            processors: [
                require('postcss-custom-properties'),
                require('postcss-custom-media'),
                require('postcss-custom-selectors'),
                require('postcss-color-gray'),
                require('postcss-color-function'),
                require('autoprefixer')({
                    browsers: 'last 2 versions'
                }),
                require('cssnano')
            ]
        },
        files: [{
            expand: true,
            cwd: 'app/Resources/assets/css',
            src: '*.css',
            dest: 'web/css/portal.min.css'
        }]
    }
},
```

**Comment by nDmitry** [comment]
You can use grunt-contrib-concat plugin to build a single file and then run grunt-postcss on it.

**Comment by redaxmedia** [comment]
Why do you close this issue? I think this is an valid feature request, closing does not solve it.

**Comment by nDmitry** [comment]
This plugin does one thing, concatenation is another)

**Comment by redaxmedia** [comment]
Do you think it is a good option to couple different task with different configuration? There is a reason Gulp and the concept of pipelines was invented. Think about it, Grunt is not made for the suggested approach.

**Comment by nDmitry** [comment]
For grunt, yes, I think so. Gulp has a different approach. As far as I know, you don't have to reinvent the wheel in gulp to merge streams into one file. Here I would need to implement grunt-contrib-concat functionality in my plugin. So I think Unix philosophy suits Grunt better.
