### ISSUE TITLE
Grunt 1.0.0 support

### ISSUE THREAD

**Issue by Cornally** [nDmitry/grunt-postcss#92]
The module fails to install with Grunt 1.0.0 (as expected, the docs state ~.0.4).  Are there plans to bring support to the newest version? Thanks for all the hard work!

**Comment by nDmitry** [comment]
It is supported https://github.com/nDmitry/grunt-postcss/blob/master/package.json#L44

**Comment by Cornally** [comment]
Bingo, I had an embarrassingly old version of node (v0.10) running which was complaining about peer dependencies, even though you had the correct peerDependency specified ( "grunt": ">=0.4.5").  Thanks for the quick response.

**Comment by brutalcrozt** [comment]
let's close this
