### ISSUE TITLE
NodeJS 0.10.x support

### ISSUE THREAD

**Issue by ntwb** [nDmitry/grunt-postcss#96]
Not looking to resolve this issue, have worked around it by updating to NodeJS 0.12.x 
but I wanted to note it here anyways @nDmitry, feel free to close it once read  😄 

When NodeJS 0.10.x support was removed in https://github.com/nDmitry/grunt-postcss/commit/180b68a7a2f74bc2372b9c9c62de6cbdf2bfa45d there was no change to the PostCSS dependancy, it was and still is `"postcss": "^5.0.0"`

The issue with this semver range is that if someone "pinned" `grunt-postcss` `0.7.0` as they still required NodeJS `0.10.x` support up until PostCSS `5.0.6` this would've been fine, but once PostCSS `5.0.6` shipped with NodeJS `0.10.x` support removed installing `grunt-postcss` `0.7.0` would install a PostCSS version that required NodeJS `0.12.x` anyway.

**Comment by nDmitry** [comment]
I don't want to fix postcss dependency version because I would have to update it manually every time. Perhaps they should bump major version when dropping support for previous node versions–that's a breaking change.
